### ISSUE TITLE
CLI for M365 version for script "Delete orphaned temporary site pages"

### ISSUE THREAD

**Issue by Adam-it** [pnp/script-samples#358]
## 🎯Aim
The aim of this issue would be to add a [CLI for M365](https://pnp.github.io/cli-microsoft365/) version of script [Delete orphaned temporary site pages](https://pnp.github.io/script-samples/spo-delete-orphaned-temporary-sitepages/README.html?tabs=pnpps).

## 🤔How
I think one of the best approach would be to use 
- [spo page list](https://pnp.github.io/cli-microsoft365/cmd/spo/page/page-list/)
- [spo page remove](https://pnp.github.io/cli-microsoft365/cmd/spo/page/page-remove/)

**Comment by reshmee011** [comment]
Please assign to me:)

**Comment by pkbullock** [comment]
Thank you @reshmee011 here as well 😃

**Comment by reshmee011** [comment]
@Adam-it : Hope you are doing o.k., wonder if you can help with the [spo page list](https://pnp.github.io/cli-microsoft365/cmd/spo/page/page-list/) commadlet. When I am running the commandlet in PowerShell using the ConvertFrom-Json to help with manupilating the data, I am getting the following error _"ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from 
the string contains the duplicated keys 'Id' and 'ID'."_

Example of commandlet run 
`
m365 spo page list -u "https://reshmeeauckloo.sharepoint.com/sites/Estimator" | ConvertFrom-Json 
ConvertFrom-Json : Cannot convert the JSON string because a dictionary that was converted from 
the string contains the duplicated keys 'Id' and 'ID'.
`
Sample of data returned with the duplicate 'Id' and 'ID'
'
"ListItemAllFields": {
      "FileSystemObjectType": 0,
      "Id": 2,
      "ServerRedirectedEmbedUri": null,
      "ServerRedirectedEmbedUrl": "",
      "ContentTypeId": "0x0101009D1CB255DA76424F860D91F20E6C4118006AF19788D1B0BB4A83BCD6E32AE8D5
75",....
      "OData__OriginalSourceWebId": null,
      "OData__OriginalSourceListId": null,
      "OData__OriginalSourceItemId": null,
      "OData__SPCallToAction": null,
      "ID": 2,
      "Created": "2021-05-05T03:57:14",
      "AuthorId": 11,
      "Modified": "2021-05-05T03:57:16",
      "EditorId": 11,
      "OData__CopySource": null,
      "CheckoutUserId": 11,
      "OData__UIVersionString": "0.1",
      "GUID": "7a12f576-82df-41b8-a99b-58ba6aa939e1"
    }
`
Any suggestion or advice is welcome.

**Comment by Adam-it** [comment]
@reshmee011 thanks for reaching out 🙂 Your rock 🤩🤩
Yes there is a hack/trick around it. Simply replace one `id` with `_id` and then convert. You may do all this in one line like 
`m365 spo page list --webUrl "https://reshmeeauckloo.sharepoint.com/sites/Estimator" | ForEach-Object { $_.replace("Id", "_Id") } | ConvertFrom-Json`

Hope that helps 👍
Let me know if I may help you in any different kind of way 👍 and thanks for your awesome contributions 💪

**Comment by reshmee011** [comment]
@Adam-it : The trick did the job though you would not expect duplicate Id fields with different case, hopefully I will finish working on the sample script for cli m365 soon.

**Comment by Adam-it** [comment]
> @Adam-it : The trick did the job though you would not expect duplicate Id fields with different case, hopefully I will finish working on the sample script for cli m365 soon.

No rush 👍. Thanks for your awesome contributions.  You rock 🤩
